In [2]:
import numpy as np

In [3]:
def is_reflexive(R):
    return np.all(np.diag(R) == 1)

def is_antireflexive(R):
    return np.all(np.diag(R) == 0)

def is_symmetric(R):
    return np.array_equal(R, R.T)

def is_asymmetric(R):
    return np.all((R & R.T) == 0)

def is_antisymmetric(R):
    return np.all((R & R.T) * (1 - np.eye(R.shape[0])) == 0)

def is_transitive(R):
    R_squared = np.linalg.matrix_power(R, 2)
    return np.all((R_squared >= R) | (R_squared == 0))

def find_elements(R):
    n = R.shape[0]
    
    greatest = [i for i in range(n) if all(R[i, j] == 1 for j in range(n))]
    
    least = [i for i in range(n) if all(R[j, i] == 1 for j in range(n))]
    
    maximal = [i for i in range(n) if not any(R[j, i] == 1 and i != j for j in range(n))]
    
    minimal = [i for i in range(n) if not any(R[i, j] == 1 and i != j for j in range(n))]
    
    return greatest, least, maximal, minimal

def inverse_relation(R):
    return R.T 

def complement_relation(R):
    n = R.shape[0]
    return (1 - R) * (1 - np.eye(n, dtype=int))  


R = np.array([[1, 1, 0, 1, 0],
              [1, 1, 1, 1, 1],
              [1, 0, 1, 1, 0],
              [1, 0, 1, 1, 0],
              [0, 1, 0, 0, 0]])

print("Рефлексивне:", is_reflexive(R))
print("Антирефлексивне:", is_antireflexive(R))
print("Симетричне:", is_symmetric(R))
print("Асиметричне:", is_asymmetric(R))
print("Антисиметричне:", is_antisymmetric(R))
print("Транзитивне:", is_transitive(R))

greatest, least, maximal, minimal = find_elements(R)
inverse_R = inverse_relation(R)
complement_R = complement_relation(R)

print("Найбільший елемент:", greatest)
print("Найменший елемент:", least)
print("Максимальні елементи:", maximal)
print("Мінімальні елементи:", minimal, "\n")
print("Обернене відношення:\n", inverse_R, "\n")
print("Доповнене відношення:\n", complement_R)


Рефлексивне: False
Антирефлексивне: False
Симетричне: False
Асиметричне: False
Антисиметричне: False
Транзитивне: True
Найбільший елемент: [1]
Найменший елемент: []
Максимальні елементи: []
Мінімальні елементи: [] 

Обернене відношення:
 [[1 1 1 1 0]
 [1 1 0 0 1]
 [0 1 1 1 0]
 [1 1 1 1 0]
 [0 1 0 0 0]] 

Доповнене відношення:
 [[0 0 1 0 1]
 [0 0 0 0 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [1 0 1 1 0]]
